### Building a Sequential model

In [15]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

*Build a feedforwad neural network model*

In [3]:
model = Sequential([
                    Flatten(input_shape=(28, 28)),
                    Dense(16, activation='relu', name='Layer_1'),
                    Dense(16, activation='relu'),
                    Dense(10),
                    Softmax()
])

In [4]:
model.weights

[<tf.Variable 'Layer_1/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.06301055, -0.08132504, -0.05259486, ...,  0.04865314,
          0.08328523,  0.050411  ],
        [ 0.00599205, -0.04060857,  0.00289503, ..., -0.04732455,
         -0.0319016 ,  0.0790136 ],
        [ 0.02945758, -0.0562286 ,  0.01273584, ..., -0.07277559,
          0.01154345,  0.00820509],
        ...,
        [-0.02527129,  0.08451581, -0.07310853, ...,  0.03364032,
          0.01612834, -0.06955538],
        [-0.04148163, -0.06519759, -0.02301122, ...,  0.0048274 ,
         -0.01135999,  0.03205464],
        [ 0.03667723, -0.06995991, -0.03727181, ..., -0.03198668,
          0.05561635, -0.06795329]], dtype=float32)>,
 <tf.Variable 'Layer_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-0.17129016, -0.22411646,  0.35833147,  0.14876

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
Layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense (Dense)                (None, 16)                272       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                170       
_________________________________________________________________
softmax (Softmax)            (None, 10)                0         
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


### The compile method
Compile the model

In [18]:
# Define the model optimizer, loss function and metrics

opt = tf.keras.optimizers.Adam(learning_rate=0.005)
acc = tf.keras.metrics.Accuracy()
mae = tf.keras.metrics.MeanAbsoluteError()

model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=[acc, mae])

In [19]:
print(model.loss)
print(model.optimizer)
print(model.metrics)
print(model.optimizer.lr)

sparse_categorical_crossentropy
[]
<tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.005>
