### Building a Sequential model

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

*Build a feedforwad neural network model*

In [13]:
model = Sequential([
                    Flatten(input_shape=(28, 28)),
                    Dense(16, activation='relu', name='Layer_1'),
                    Dense(16, activation='relu'),
                    Dense(10),
                    Softmax()
])

In [8]:
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[ 0.07271583, -0.05520491,  0.00765514, ..., -0.02282282,
          0.00722988, -0.03593117],
        [ 0.0294073 , -0.03545611, -0.03232308, ..., -0.02918986,
          0.02954539, -0.00578138],
        [-0.07120267,  0.05558871,  0.0428587 , ...,  0.04817452,
          0.01343646, -0.06585586],
        ...,
        [ 0.00443131, -0.06668785,  0.05954559, ..., -0.0802094 ,
         -0.03977958, -0.06345049],
        [-0.04873293, -0.06715234, -0.01092457, ..., -0.00867559,
          0.01039826, -0.02905839],
        [-0.05046725, -0.08586835, -0.06709492, ...,  0.00902107,
         -0.00791734,  0.07948259]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-0.07573652, -0.2846595 , -0.2517715 ,  0.232

In [14]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
Layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense_11 (Dense)             (None, 16)                272       
_________________________________________________________________
dense_12 (Dense)             (None, 10)                170       
_________________________________________________________________
softmax_2 (Softmax)          (None, 10)                0         
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________
